"use client";

import * as React from "react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import { Download, FileText } from "@/lib/icons";

interface GeneratedReport {
  id: string;
  title: string;
  year: number;
  quarter: string;
  s3Key: string | null;
  fileSize: number | null;
  generatedAt: Date;
  generatedBy: { name: string } | null;
}

interface GeneratedReportsListProps {
  reports: GeneratedReport[];
}

/**
 * R29: Display generated report history with re-download links.
 * Shows all previously generated reports (PDF + XLSX) tracked in BoardReport.
 */
export function GeneratedReportsList({ reports }: GeneratedReportsListProps) {
  const formatFileSize = (bytes: number | null) => {
    if (!bytes) return "—";
    if (bytes < 1024) return `${bytes} B`;
    if (bytes < 1024 * 1024) return `${Math.round(bytes / 1024)} KB`;
    return `${(bytes / (1024 * 1024)).toFixed(1)} MB`;
  };

  return (
    <Card>
      <CardHeader>
        <CardTitle className="flex items-center gap-2">
          <FileText className="h-5 w-5" />
          Generated Reports
        </CardTitle>
      </CardHeader>
      <CardContent>
        {reports.length === 0 ? (
          <p className="text-muted-foreground py-4 text-center">
            No reports generated yet.
          </p>
        ) : (
          <Table>
            <TableHeader>
              <TableRow>
                <TableHead>Report</TableHead>
                <TableHead>Period</TableHead>
                <TableHead>Generated By</TableHead>
                <TableHead>Date</TableHead>
                <TableHead>Size</TableHead>
                <TableHead>Actions</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {reports.map((report) => {
                const isDraft = report.title.includes("DRAFT");
                const isPdf = report.title.includes("PDF");
                return (
                  <TableRow key={report.id}>
                    <TableCell>
                      <div className="flex items-center gap-2">
                        <span className="text-sm font-medium">
                          {report.title}
                        </span>
                        {isDraft && <Badge variant="outline">Draft</Badge>}
                      </div>
                    </TableCell>
                    <TableCell>
                      {report.quarter} {report.year}
                    </TableCell>
                    <TableCell className="text-muted-foreground text-sm">
                      {report.generatedBy?.name ?? "System"}
                    </TableCell>
                    <TableCell className="text-muted-foreground text-sm">
                      {new Date(report.generatedAt).toLocaleDateString(
                        "en-IN",
                        {
                          day: "numeric",
                          month: "short",
                          year: "numeric",
                          hour: "2-digit",
                          minute: "2-digit",
                        },
                      )}
                    </TableCell>
                    <TableCell className="text-sm">
                      {formatFileSize(report.fileSize)}
                    </TableCell>
                    <TableCell>
                      {report.s3Key ? (
                        <Button variant="ghost" size="sm" asChild>
                          <a
                            href={`/api/download?key=${encodeURIComponent(report.s3Key)}`}
                            target="_blank"
                            rel="noopener noreferrer"
                          >
                            <Download className="mr-1 h-4 w-4" />
                            {isPdf ? "PDF" : "XLSX"}
                          </a>
                        </Button>
                      ) : (
                        <span className="text-muted-foreground text-sm">
                          N/A
                        </span>
                      )}
                    </TableCell>
                  </TableRow>
                );
              })}
            </TableBody>
          </Table>
        )}
      </CardContent>
    </Card>
  );
}
